services:
  monitoring-redis:
    image: redis:7.4-alpine
    container_name: monitoring-redis
    ports:
      - "12004:6379"
    environment:
      TZ: Asia/Seoul
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - monitoring-argus-net

networks:
  monitoring-argus-net:
    name: monitoring-argus-net
    driver: bridge

volumes:
  redis-data:
    name: redis-data
