{
 "title": "main_dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU_USAGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (application, instance) (avg_over_time(process_cpu_usage[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HEAP_USAGE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application, instance) (jvm_memory_used_bytes{area=\"heap\"})\r\n/\r\nsum by (application, instance) (jvm_memory_max_bytes{area=\"heap\"})\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC_AVG_DURATION",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application, instance) (\r\n  increase(jvm_gc_pause_seconds_sum[1m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (application, instance) (\r\n    increase(jvm_gc_pause_seconds_count[1m])\r\n  ),\r\n  1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by (application, instance) (increase(jvm_gc_pause_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HEAP_OLD_GEN_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (application, instance) (\r\n  jvm_memory_used_bytes{area=\"heap\", id=~\".*Old Gen|.*Tenured Gen\"}\r\n)\r\n/\r\nsum by (application, instance) (\r\n  jvm_memory_max_bytes{area=\"heap\", id=~\".*Old Gen|.*Tenured Gen\"}\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ACTIVE_THREADS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by (application, instance) (jvm_threads_live_threads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PEAK_THREADS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "avg by (application, instance) (jvm_threads_peak_threads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAEMON_THREADS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "avg by (application, instance) (jvm_threads_daemon_threads)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}