{
 "title": "sub_dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "HTTP_P99_RESPONSE_TIME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (application, instance, uri, le) (\r\n    rate(http_server_requests_seconds_bucket{\r\n      uri!~\"/actuator.*|/swagger.*|/v3/api-docs.*\"\r\n    }[1m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP_RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri!~\"/actuator.*|/swagger.*|/v3/api-docs.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP_ERROR_RATE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application, instance, uri) (\r\n  rate(http_server_requests_seconds_count{status=~\"5..\"}[1m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (application, instance, uri) (\r\n    rate(http_server_requests_seconds_count[1m])\r\n  ),\r\n  1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIKARI_ACTIVE_CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_active[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIKARI_PENDING_CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(hikaricp_connections_pending[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HIKARI_USAGE_RATIO",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active / clamp_min(hikaricp_connections_max, 1) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}